<?php
	$holidayYear = filter_input(INPUT_GET, 'year', FILTER_VALIDATE_INT, array('options' => array('min_range' => 2000, 'max_range' => 2100))) ?: (int) date('Y');
	$holidayRows = array(); $holidayYears = array($holidayYear); $holidayError = null; $holidayMessage = null;
	$holidayUser = trim((string) ($_SESSION['d2s8wu_uname'] ?? $_SESSION['d2s8wu_uid'] ?? 'System'));
	$holidayAgencyCode = trim((string) ($_SESSION['d2s8wu_officecode'] ?? ''));
	$holidayAgencyName = trim((string) ($_SESSION['d2s8wu_officetitle'] ?? $_SESSION['d2s8wu_officeabrv'] ?? ''));
	if (empty($_SESSION['holidays_csrf'])) $_SESSION['holidays_csrf'] = bin2hex(random_bytes(32));
	function holidayRecord($date, $name, $id) { $date = new DateTime($date); return array('id' => $id, 'name' => $name, 'month' => $date->format('F'), 'mthree' => $date->format('M'), 'mno' => (int) $date->format('n'), 'mnumbr' => $date->format('m'), 'day' => (int) $date->format('j'), 'dayno' => $date->format('d'), 'year' => (int) $date->format('Y')); }
	$philippine2026 = array(
		holidayRecord('2026-01-01', "New Year's Day", 'PH-2026-NEW-YEAR'), holidayRecord('2026-02-17', 'Chinese New Year', 'PH-2026-CHINESE-NEW-YEAR'), holidayRecord('2026-02-25', 'EDSA People Power Revolution Anniversary', 'PH-2026-EDSA'), holidayRecord('2026-03-20', "Eid'l Fitr", 'PH-2026-EID-FITR'), holidayRecord('2026-04-02', 'Maundy Thursday', 'PH-2026-MAUNDY-THURSDAY'), holidayRecord('2026-04-03', 'Good Friday', 'PH-2026-GOOD-FRIDAY'), holidayRecord('2026-04-04', 'Black Saturday', 'PH-2026-BLACK-SATURDAY'), holidayRecord('2026-04-09', 'Araw ng Kagitingan', 'PH-2026-ARAW-NG-KAGITINGAN'), holidayRecord('2026-05-01', 'Labor Day', 'PH-2026-LABOR-DAY'), holidayRecord('2026-05-27', "Eid'l Adha", 'PH-2026-EID-ADHA'), holidayRecord('2026-06-12', 'Independence Day', 'PH-2026-INDEPENDENCE-DAY'), holidayRecord('2026-08-21', 'Ninoy Aquino Day', 'PH-2026-NINOY-AQUINO-DAY'), holidayRecord('2026-08-31', 'National Heroes Day', 'PH-2026-NATIONAL-HEROES-DAY'), holidayRecord('2026-11-01', "All Saints' Day", 'PH-2026-ALL-SAINTS-DAY'), holidayRecord('2026-11-02', "All Souls' Day", 'PH-2026-ALL-SOULS-DAY'), holidayRecord('2026-11-30', 'Bonifacio Day', 'PH-2026-BONIFACIO-DAY'), holidayRecord('2026-12-08', 'Feast of the Immaculate Conception of Mary', 'PH-2026-IMMACULATE-CONCEPTION'), holidayRecord('2026-12-24', 'Christmas Eve', 'PH-2026-CHRISTMAS-EVE'), holidayRecord('2026-12-25', 'Christmas Day', 'PH-2026-CHRISTMAS-DAY'), holidayRecord('2026-12-31', 'Last Day of the Year', 'PH-2026-LAST-DAY')
	);
	try {
		$holidayCnn = new PDO("mysql:host={$host};dbname={$db}", $uname, $pw); $holidayCnn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
		$holidayCnn->exec("CREATE TABLE IF NOT EXISTS holidays_tbl (holidays_autoid INT NOT NULL AUTO_INCREMENT, agency_code TEXT NOT NULL, agency_name TEXT NOT NULL, holidays_id TEXT NOT NULL, holiday_name TEXT NOT NULL, holiday_month TEXT NOT NULL, holiday_mthree VARCHAR(3) NOT NULL, holiday_mno INT NOT NULL, holiday_mnumbr VARCHAR(2) NOT NULL, holiday_day INT NOT NULL, holiday_dayno VARCHAR(2) NOT NULL, holiday_year INT NOT NULL, xdel INT NOT NULL DEFAULT 0, createdby TEXT NOT NULL, modifiedby TEXT NOT NULL, modified_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (holidays_autoid), KEY holiday_year_date_index (holiday_year, holiday_mno, holiday_day)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
		if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['holiday_action'])) {
			if (!hash_equals($_SESSION['holidays_csrf'], (string) ($_POST['holidays_csrf'] ?? ''))) $holidayError = 'Your holiday session has expired. Please try again.';
			elseif ($_POST['holiday_action'] === 'delete') { $delete = $holidayCnn->prepare("UPDATE holidays_tbl SET xdel=1, modifiedby=:user WHERE holidays_autoid=:id"); $delete->execute(array(':user'=>$holidayUser, ':id'=>(int) ($_POST['holiday_id'] ?? 0))); $holidayMessage = $delete->rowCount() ? 'Holiday deleted.' : 'Holiday could not be deleted.'; }
			else {
				$name = trim((string) ($_POST['holiday_name'] ?? '')); $date = trim((string) ($_POST['holiday_date'] ?? '')); $id = (int) ($_POST['holiday_id'] ?? 0); $dateObject = DateTime::createFromFormat('Y-m-d', $date);
				if ($name === '' || !$dateObject || $dateObject->format('Y-m-d') !== $date) $holidayError = 'Please enter a holiday name and a valid date.';
				else { $record = holidayRecord($date, $name, '');
					$params = array(':name'=>$record['name'], ':month'=>$record['month'], ':mthree'=>$record['mthree'], ':mno'=>$record['mno'], ':mnumbr'=>$record['mnumbr'], ':day'=>$record['day'], ':dayno'=>$record['dayno'], ':year'=>$record['year'], ':user'=>$holidayUser);
					if ($id) { $params[':id']=$id; $save=$holidayCnn->prepare("UPDATE holidays_tbl SET holiday_name=:name,holiday_month=:month,holiday_mthree=:mthree,holiday_mno=:mno,holiday_mnumbr=:mnumbr,holiday_day=:day,holiday_dayno=:dayno,holiday_year=:year,modifiedby=:user WHERE holidays_autoid=:id AND xdel=0"); $save->execute($params); $holidayMessage='Holiday updated.'; }
					else { $nextHolidayId = (int) $holidayCnn->query("SELECT COALESCE(MAX(CAST(holidays_id AS UNSIGNED)), 0) + 1 FROM holidays_tbl")->fetchColumn(); $params += array(':agency_code'=>$holidayAgencyCode, ':agency_name'=>$holidayAgencyName, ':holidays_id'=>(string)$nextHolidayId); $save=$holidayCnn->prepare("INSERT INTO holidays_tbl (agency_code,agency_name,holidays_id,holiday_name,holiday_month,holiday_mthree,holiday_mno,holiday_mnumbr,holiday_day,holiday_dayno,holiday_year,xdel,createdby,modifiedby) VALUES (:agency_code,:agency_name,:holidays_id,:name,:month,:mthree,:mno,:mnumbr,:day,:dayno,:year,0,:user,:user)"); $save->execute($params); $holidayMessage='Custom holiday created.'; }
				}
			}
		}
		if ($holidayYear === 2026) {
			$existing = $holidayCnn->prepare("SELECT holiday_name, holiday_mno, holiday_day FROM holidays_tbl WHERE holiday_year=2026"); $existing->execute(); $known = array(); foreach ($existing->fetchAll(PDO::FETCH_ASSOC) as $row) $known[strtolower(trim($row['holiday_name'])) . '|' . $row['holiday_mno'] . '|' . $row['holiday_day']] = true;
			$missing = array_filter($philippine2026, function ($holiday) use ($known) { return !isset($known[strtolower($holiday['name']) . '|' . $holiday['mno'] . '|' . $holiday['day']]); });
			if ($missing) { $nextHolidayId = (int) $holidayCnn->query("SELECT COALESCE(MAX(CAST(holidays_id AS UNSIGNED)), 0) FROM holidays_tbl")->fetchColumn(); $insert=$holidayCnn->prepare("INSERT INTO holidays_tbl (agency_code,agency_name,holidays_id,holiday_name,holiday_month,holiday_mthree,holiday_mno,holiday_mnumbr,holiday_day,holiday_dayno,holiday_year,xdel,createdby,modifiedby) VALUES ('PH','Philippines',:id,:name,:month,:mthree,:mno,:mnumbr,:day,:dayno,:year,0,'Philippine holiday sync','Philippine holiday sync')"); foreach ($missing as $holiday) { $nextHolidayId++; $insert->execute(array(':id'=>(string)$nextHolidayId,':name'=>$holiday['name'],':month'=>$holiday['month'],':mthree'=>$holiday['mthree'],':mno'=>$holiday['mno'],':mnumbr'=>$holiday['mnumbr'],':day'=>$holiday['day'],':dayno'=>$holiday['dayno'],':year'=>$holiday['year'])); } $holidayMessage = count($missing) . ' Philippine holiday' . (count($missing) === 1 ? '' : 's') . ' added.'; }
		}
		$years = $holidayCnn->query("SELECT DISTINCT holiday_year FROM holidays_tbl WHERE xdel=0 ORDER BY holiday_year DESC")->fetchAll(PDO::FETCH_COLUMN); $holidayYears = array_values(array_unique(array_merge(array($holidayYear, (int) date('Y')), array_map('intval', $years)))); rsort($holidayYears);
		$list = $holidayCnn->prepare("SELECT * FROM holidays_tbl WHERE holiday_year=:year AND xdel=0 ORDER BY holiday_mno DESC,holiday_day DESC,holiday_name ASC"); $list->execute(array(':year'=>$holidayYear)); $holidayRows=$list->fetchAll(PDO::FETCH_ASSOC);
	} catch (PDOException $exception) { $holidayError='Holidays are temporarily unavailable.'; }
?>
<div class="pt-3"><div class="d-flex justify-content-between align-items-start mb-4"><div><h5 class="mb-1 fw-bold text-light">Holidays</h5><p class="text-muted mb-0">Philippine holidays and your custom holiday entries.</p></div><form method="get"><label class="form-label small mb-1" for="holiday-year">Year</label><select class="form-select" id="holiday-year" name="year" onchange="this.form.submit()"><?php foreach ($holidayYears as $year): ?><option value="<?php echo (int)$year; ?>" <?php echo $year===$holidayYear?'selected':''; ?>><?php echo (int)$year; ?></option><?php endforeach; ?></select></form></div>
<?php if ($holidayMessage): ?><div class="alert alert-success"><?php echo htmlspecialchars($holidayMessage); ?></div><?php endif; ?><?php if ($holidayError): ?><div class="alert alert-danger"><?php echo htmlspecialchars($holidayError); ?></div><?php endif; ?>
<div class="card"><div class="card-body"><div class="d-flex justify-content-end mb-3"><button type="button" class="btn btn-primary" id="new-holiday" data-bs-toggle="modal" data-bs-target="#holiday-modal"><i class="fas fa-plus"></i> Custom Holiday</button></div><div class="table-responsive"><table id="holiday-list" class="table table-dark table-striped table-hover align-middle"><thead><tr><th>Date</th><th>Holiday</th><th>Agency</th><th>Created By</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach ($holidayRows as $holiday): $date=sprintf('%04d-%02d-%02d',$holiday['holiday_year'],$holiday['holiday_mno'],$holiday['holiday_day']); ?><tr><td data-order="<?php echo htmlspecialchars($date); ?>"><?php echo htmlspecialchars(date('M j, Y',strtotime($date))); ?></td><td><?php echo htmlspecialchars($holiday['holiday_name']); ?></td><td><?php echo htmlspecialchars($holiday['agency_name']); ?></td><td><?php echo htmlspecialchars($holiday['createdby']); ?></td><td class="text-end text-nowrap"><button type="button" class="btn btn-sm btn-outline-info edit-holiday" data-id="<?php echo (int)$holiday['holidays_autoid']; ?>" data-name="<?php echo htmlspecialchars($holiday['holiday_name'],ENT_QUOTES); ?>" data-date="<?php echo htmlspecialchars($date); ?>" data-bs-toggle="modal" data-bs-target="#holiday-modal" title="Edit"><i class="fas fa-edit"></i></button> <form method="post" class="d-inline" onsubmit="return confirm('Delete this holiday?');"><input type="hidden" name="holidays_csrf" value="<?php echo htmlspecialchars($_SESSION['holidays_csrf']); ?>"><input type="hidden" name="holiday_action" value="delete"><input type="hidden" name="holiday_id" value="<?php echo (int)$holiday['holidays_autoid']; ?>"><button class="btn btn-sm btn-outline-danger" type="submit" title="Delete"><i class="fas fa-trash"></i></button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<div class="modal fade" id="holiday-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><form method="post" class="modal-content"><div class="modal-header"><h5 class="modal-title" id="holiday-modal-title">Create Custom Holiday</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="holidays_csrf" value="<?php echo htmlspecialchars($_SESSION['holidays_csrf']); ?>"><input type="hidden" name="holiday_action" value="save"><input type="hidden" name="holiday_id" id="holiday-id"><div class="mb-3"><label class="form-label">Holiday Name</label><input class="form-control" required name="holiday_name" id="holiday-name"></div><div><label class="form-label">Date</label><input class="form-control" required type="date" name="holiday_date" id="holiday-date"></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save Holiday</button></div></form></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){ $('#holiday-list').DataTable({order:[[0,'desc']],lengthMenu:[[5,10,25,50,100,-1],[5,10,25,50,100,'All']]}); const modal=document.getElementById('holiday-modal'),title=document.getElementById('holiday-modal-title'),id=document.getElementById('holiday-id'),name=document.getElementById('holiday-name'),date=document.getElementById('holiday-date'); document.getElementById('new-holiday').onclick=function(){title.textContent='Create Custom Holiday';id.value='';name.value='';date.value='';}; document.querySelectorAll('.edit-holiday').forEach(button=>button.onclick=function(){title.textContent='Edit Holiday';id.value=this.dataset.id;name.value=this.dataset.name;date.value=this.dataset.date;});});</script>
